### ISSUE TITLE
Creating a BRD Document in Whimsical

### ISSUE THREAD

**Issue by ersankarimi** [FE-14/greenpeace-frontend#1]
Buat Dokumen BRD di situs web Whimsical

**Comment by meilyanaanisa** [comment]
Pembuatan BRD tentang 
-  project decription tujuan utama dari project dan kenapa membuat project itu.

- project scope, batasan lingkup project 
 yang berada di lingkup dan juga diluar lingkup 

- membuat user flow, langkah langkah penggunaan pada website 

- current process, pengerjaan yang sedang dikerjakan

**Comment by meilyanaanisa** [comment]
Tgl 18 octo 2022 

Mengerjakan proposed process, mengenai apa yg diajukan untuk pembuatan project.

Functional recuirement, persyaratan fungsional pengerjakan yg harus dilakukan hingga apabila fitur itu tidak ada web masih bisa berjalan.

**Comment by meilyanaanisa** [comment]
Menyelesaikan BRD menghilangkan functional requirement dan menambahkan 

Target user, tujuan pengguna 
Glossary, istilah kata pada BRD
References, link referensi yang berkaitan dengan brd
Document History, history document disetiap versi

**Comment by meilyanaanisa** [comment]
Target user, tujuan pengguna yg diinginkan
Glossary, penggunaan kata pada BRD
References, link yg berhubungan dengan BRD
Document History, perubahan yang terjadi

BRD SUDAH SELESAI
