### ISSUE TITLE
Membuat slidedeck presentasi

### ISSUE THREAD

**Issue by ersankarimi** [FE-14/greenpeace-frontend#3]
@intanpermata11 @meilyanaanisa @ersankarimi 

Jangan lupa untuk buat slidedeck presentation nanti nya

**Comment by meilyanaanisa** [comment]
Proses pembuatan slidedeck melalui aplikasi canva
- OUTLINE BRD 
- OUTLINE UI/UX
- Coding development
- Deployment
- Slidedeck and Presentation

SLIDEDECK SELESAI

**Comment by ersankarimi** [comment]
> Proses pembuatan slidedeck melalui aplikasi canva
> 
> * OUTLINE BRD
> * OUTLINE UI/UX
> * Coding development
> * Deployment
> * Slidedeck and Presentation
> 
> SLIDEDECK SELESAI

@meilyanaanisa @intanpermata11 tolong sertakan link ppt nya baru ku close ini issue

**Comment by meilyanaanisa** [comment]
Proses pembuatan slidedeck melalui aplikasi canva

OUTLINE BRD

OUTLINE UI/UX

Coding development

Deployment

Slidedeck and Presentation 

Proses pembuatan slidedeck melalui aplikasi canva

OUTLINE BRD

OUTLINE UI/UX

Coding development

Deployment

Slidedeck and Presentation 

- Link Presentation 

https://www.canva.com/design/DAFPxZyUgys/-P9bDX0nt3OQsOSS-8ouQg/edit?layoutQuery=SLIDE+DECK


SLIDEDECK SELESAI

**Comment by ersankarimi** [comment]
Oke siap makasih banyak. Aku close issue ini
