### ISSUE TITLE
Buat 3 halaman utama website

### ISSUE THREAD

**Issue by ersankarimi** [FE-14/greenpeace-frontend#6]
Membuat 3 halaman utama website:
[ ] Beranda @ersankarimi 
[ ] Halaman artikel @intanpermata11 @meilyanaanisa 
[ ] Baca halaman artikel @ersankarimi

**Comment by intanpermata11** [comment]
on progress sambil belajar

**Comment by intanpermata11** [comment]
iya laptopnya trouble, ini baru bisa lagi
