### ISSUE TITLE
Fix warna input pada halaman `search`

### ISSUE THREAD

**Issue by ersankarimi** [FE-14/greenpeace-frontend#80]
Atur warna dari field search input pada halaman search itu menjadi `bg-transparent`.

Perbaikin pada branch [update-search-field-on-search-page](https://github.com/FE-14/greenpeace-frontend/tree/update-search-field-on-search-page)

**Comment by meilyanaanisa** [comment]
mengganti warna input menjadi transparent

Telah Selesai..
