### ISSUE TITLE
Buat halaman `Sejarah`

### ISSUE THREAD

**Issue by ersankarimi** [FE-14/greenpeace-frontend#87]
Buat halaman sejarah di branch 'create-sejarah-page`

**Comment by intanpermata11** [comment]
page sejarah onprogress, tinggal buat title yang di atas sama komponen bawahnya juga masih onprogress

**Comment by intanpermata11** [comment]
@ersankarimi komponen yang "Lainnya Tentang Kami" masih unfixed, tapi udah dipush

**Comment by intanpermata11** [comment]
History page almost done, masih unfixed

**Comment by intanpermata11** [comment]
komponen card greenpeace dan page history sudah diupdate, tinggal card title
