### ISSUE TITLE
Update dan fix bagian footer

### ISSUE THREAD

**Issue by ersankarimi** [FE-14/greenpeace-frontend#89]
Fix footer untuk gambar accent nya tidak ketampil dengan baik.

Dan update konten footer, masukkan link section dari Kenali Greenpeace seperti di design figma

Update di branch update-and-fix-footer

**Comment by intanpermata11** [comment]
footer onprogress, tinggal ngelink untuk section kenali greenpeace nya

**Comment by meilyanaanisa** [comment]
Footer sudah dapat menuju link kenali greenpeace
